name: Feed to social media
on:
  workflow_dispatch:

jobs:
  Feed2SocialMedia:
    runs-on: ubuntu-latest
    steps:
      - name: Feed to social media
        uses: lwojcik/github-action-feed-to-social-media@v2
        with:
          feedUrl: 'https://shop.erinstylr.online/a/rssfeed?type=collection&key=allproduct'
          # newestItemStrategy: 'latestDate'
          # postFormat: "New post: {title}\n\n{link}"
          # Twitter settings
          twitterEnable: true
          twitterPostFormat: "New post: {title}\n\n{link}"
          twitterApiKey: 'twitterApiKey'
          twitterApiKeySecret: 'twitterApiKeySecret'
          twitterAccessToken: 'twiiterAccessToken'
          twitterAccessTokenSecret: 'twitterAccessTokenSecret'
